myprops:
  defaultZone: http://localhost:10100/eureka/
  port: 10110

server:
  port: ${myprops.port}

spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: ${myprops.defaultZone}
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream,routes
zuul:
  prefix: /
  routes:
    fw-bend-server:
      path: /fw-bend-server/**
      serviceId: fw-bend-server
      sensitiveHeaders: "*"
    aqmp-bus: /**
    firmware-analyze: /**
    firmware-fetch: /**
    system-log: /**
#    unified-auth: /**
    unified-auth:
      path: /unified-auth/**
      serviceId: unified-auth
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  add-proxy-headers: true
