myprops:
  defaultZone: http://localhost:10100/eureka/
  port: 10110

server:
  port: ${myprops.port}

spring:
  application:
    name: gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: ${myprops.defaultZone}

management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream,routes

zuul:
  prefix: /
  routes:
    fw-bend-server:
      path: /fw-bend-server/**
      serviceId: fw-bend-server
      sensitiveHeaders: "*"
    aqmp-bus:
      path: /aqmp-bus/**
      serviceId: aqmp-bus
      sensitiveHeaders: "*"
    firmware-analyze:
      path: /firmware-analyze/**
      serviceId: firmware-analyze
      sensitiveHeaders: "*"
    firmware-fetch:
      path: /firmware-fetch/**
      serviceId: firmware-fetch
      sensitiveHeaders: "*"
    system-log:
      path: /system-log/**
      serviceId: system-log
      sensitiveHeaders: "*"
    unified-auth:
      path: /unified-auth/**
      serviceId: unified-auth
      sensitiveHeaders: "*"
    embed_terminal:
      path: /embed_terminal/**
      serviceId: embed_terminal
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  add-proxy-headers: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

#设置hystrix的熔断时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #设置API网关中路由转发请求的HystrixCommand执行超时时间
            timeoutInMilliseconds: 30000