
# 后台服务
myprops:
  defaultZone: http://192.168.1.100:10100/eureka/
  gateway: http://192.168.1.100:10110/
  port: 10901
  devEnvIP: 192.168.1.100
  mysql:
    ip: ${myprops.devEnvIP}
    port: 13306
  rabbitmq:
    ip: ${myprops.devEnvIP}
    port: 5672

spring:
  application:
    name: fw-bend-server
  rabbitmq:
    host: ${myprops.rabbitmq.ip}
    port: ${myprops.rabbitmq.port}
    username: admin
    password: admin
  cloud:
    bus:
      enabled: true
    trace:
      enabled: true
  data:
    mongodb:
      uri: mongodb://admin:123456@${myprops.devEnvIP}:27017/cnvd_db?authSource=admin&authMechanism=SCRAM-SHA-1
  datasource:
    # mysql database config
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${myprops.mysql.ip}:${myprops.mysql.port}/vulner_cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

    # 下面为连接池的补充设置，应用到上面所有数据源中
    #自动提交
    default-auto-commit: true
    #指定updates是否自动提交
    auto-commit: true
    maximum-pool-size: 100
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 18800
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000

server:
  port: ${myprops.port}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${myprops.defaultZone}

security:
  oauth2:
    resource:
      id: fw-bend-server-dev
      user-info-uri: http://192.168.1.100:10110/unified-auth/account_auth/current
      #      user-info-uri: http://localhost:1203/api/member
      prefer-token-info: false


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR