# 所有易变配置参数在此定义
myprops:
  defaultZone: http://localhost:10100/eureka/
  port: 10115
  defaultIp: 192.168.182.88

spring:
  application:
    name: aqmp-bus
  rabbitmq:
    host: ${myprops.defaultIp}
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  cloud:
    bus:
      enabled: true
    trace:
      enabled: true
server:
  port: ${myprops.port}

eureka:
  client:
    serviceUrl:
      defaultZone: ${myprops.defaultZone}

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
