
server:
  port: 10100

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/${spring.application.name}/

spring:
  application:
    name: eureka
#    name: vulner_register_hub
